export function LinePageStyles() {
  return (
    <style>{`
      .line-page{--line-accent:#fc5413;--line-ink:#171717;--line-paper:#f7f7f5;--line-soft:#ecece8;--line-muted:#666b70;--line-card:#fff;--line-border:rgba(23,23,23,.12);--line-dark:#15171b;color:var(--line-ink);background:var(--line-paper)}
      .line-page h1,.line-page h2,.line-page h3{letter-spacing:0}.line-page h1{max-width:1120px;margin:18px 0 22px;font-size:clamp(48px,7vw,104px);line-height:.94}.line-page h2{margin:12px 0 16px;font-size:clamp(34px,5vw,72px);line-height:1}.line-page p{color:var(--line-muted)}
      .reveal{animation:lineRise .75s ease both}@keyframes lineRise{from{opacity:0;transform:translateY(28px)}to{opacity:1;transform:none}}@supports (animation-timeline:view()){.reveal{animation-timeline:view();animation-range:entry 8% cover 28%}}
      @media (prefers-reduced-motion:reduce){.reveal,.line-hero-bg,.hero-video-card img{animation:none!important;transition:none!important}}

      .line-header{position:fixed;top:18px;left:clamp(14px,3vw,42px);right:clamp(14px,3vw,42px);z-index:90;display:grid;grid-template-columns:auto 1fr auto;gap:18px;align-items:center;min-height:72px;padding:10px 14px;background:rgba(255,255,255,.86);border:1px solid rgba(23,23,23,.1);border-radius:10px;box-shadow:0 18px 55px rgba(17,19,23,.12);backdrop-filter:blur(18px)}
      .line-header nav,.line-footer nav{display:flex;flex-wrap:wrap;gap:4px;justify-content:center}.line-header nav a,.catalog-trigger,.line-footer nav a{padding:10px 12px;border-radius:8px;color:#2b2f34;font-weight:800;transition:background .18s ease,transform .18s ease,color .18s ease}.line-header nav a:hover,.catalog-menu:hover .catalog-trigger{color:var(--line-accent);background:#f2f2ef;transform:translateY(-1px)}
      .line-header-contact{display:grid;gap:3px;text-align:right;font-size:14px;font-weight:950}.line-header-contact a{white-space:nowrap;transition:color .18s ease}.line-header-contact a:hover{color:var(--line-accent)}
      .catalog-menu{position:relative}.catalog-dropdown{position:absolute;top:calc(100% + 12px);left:0;display:grid;width:min(520px,80vw);padding:10px;background:#fff;border:1px solid var(--line-border);border-radius:10px;box-shadow:0 22px 70px rgba(17,19,23,.18);opacity:0;visibility:hidden;transform:translateY(8px);transition:opacity .18s ease,transform .18s ease,visibility .18s ease}.catalog-menu:hover .catalog-dropdown,.catalog-menu:focus-within .catalog-dropdown{opacity:1;visibility:visible;transform:none}.catalog-dropdown a{display:grid!important;gap:3px;padding:13px 14px}.catalog-dropdown strong{font-size:14px}.catalog-dropdown span{color:#8a8f94;font-size:12px}

      .line-hero{position:relative;min-height:100dvh;display:grid;grid-template-columns:minmax(0,1fr) minmax(360px,.48fr);gap:clamp(28px,5vw,72px);align-items:end;padding:136px clamp(18px,5vw,72px) 58px;overflow:hidden;background:linear-gradient(110deg,#fff 0%,#f4f4f1 45%,#e5e4df 100%)}
      .line-hero-bg{position:absolute;inset:0;background:radial-gradient(circle at 82% 18%,rgba(252,84,19,.16),transparent 28%),linear-gradient(rgba(23,23,23,.04) 1px,transparent 1px),linear-gradient(90deg,rgba(23,23,23,.035) 1px,transparent 1px);background-size:auto,72px 72px,72px 72px;animation:lineGridMove 12s ease-in-out infinite alternate}@keyframes lineGridMove{from{transform:scale(1)}to{transform:scale(1.02) translateX(-.8%)}}
      .line-hero-content,.hero-video-card{position:relative;z-index:1}.line-hero-content p{max-width:760px;font-size:20px}.line-kicker{display:inline-flex;align-items:center;gap:10px;color:var(--line-accent);font-size:12px;font-weight:950;text-transform:uppercase}.line-kicker:before{content:"";width:34px;height:2px;background:currentColor}.line-actions{display:flex;flex-wrap:wrap;gap:12px;margin-top:32px}
      .line-primary,.line-secondary,.primary-button,.secondary-button,.ghost-button{display:inline-flex;align-items:center;justify-content:center;gap:9px;min-height:50px;padding:0 20px;border-radius:8px;border:0;font-weight:950;cursor:pointer;transition:transform .18s ease,box-shadow .18s ease,background .18s ease}.line-primary,.primary-button{color:#fff;background:var(--line-accent);box-shadow:0 18px 42px rgba(252,84,19,.26)}.line-secondary,.secondary-button{color:var(--line-ink);background:#fff;border:1px solid var(--line-border)}.ghost-button{color:var(--line-ink);background:transparent;border:1px solid var(--line-border)}.line-primary:hover,.line-secondary:hover,.primary-button:hover,.secondary-button:hover,.ghost-button:hover{transform:translateY(-2px)}button:disabled{cursor:not-allowed;opacity:.48;transform:none!important}
      .hero-metrics{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px;margin-top:42px;max-width:960px}.hero-metrics article{padding:18px;background:rgba(255,255,255,.74);border:1px solid var(--line-border);border-radius:9px;box-shadow:0 16px 42px rgba(17,19,23,.08)}.hero-metrics strong{display:block;color:var(--line-accent);font-size:clamp(26px,3vw,42px);line-height:1}.hero-metrics span{display:block;margin-top:7px;color:#4d5359;font-weight:850}
      .hero-video-card{align-self:stretch;min-height:640px;overflow:hidden;border:1px solid var(--line-border);border-radius:12px;background:#111;box-shadow:0 28px 80px rgba(17,19,23,.2)}.hero-video-card img{width:100%;height:100%;object-fit:cover;animation:lineVideoMove 10s ease-in-out infinite alternate}@keyframes lineVideoMove{from{transform:scale(1)}to{transform:scale(1.06)}}.video-badge{position:absolute;left:22px;right:22px;bottom:22px;display:flex;align-items:center;gap:12px;padding:16px;color:#fff;background:rgba(18,20,24,.76);border:1px solid rgba(255,255,255,.16);border-radius:9px;backdrop-filter:blur(14px)}.video-badge span{width:13px;height:13px;background:var(--line-accent);border-radius:50%;box-shadow:0 0 0 8px rgba(252,84,19,.18)}

      .line-section,.line-about,.line-main-site-banner,.line-contact-form,.line-contacts,.line-banner,.calculator-shell{padding:clamp(72px,8vw,118px) clamp(18px,5vw,72px)}.line-section-head{max-width:980px;margin-bottom:36px}
      .line-catalog{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:18px}.line-catalog article,.line-cases article,.line-advantages article,.line-steps article,.line-slider article,.line-partners article,.line-form,.line-faq details,.calc-workspace,.calc-summary{background:var(--line-card);border:1px solid var(--line-border);border-radius:10px;box-shadow:0 20px 60px rgba(23,23,23,.08)}.line-catalog article{overflow:hidden;transition:transform .18s ease,box-shadow .18s ease}.line-catalog article:hover,.line-cases article:hover,.line-advantages article:hover,.line-steps article:hover,.profile-card:hover,.option-card:hover,.calc-chip:hover{transform:translateY(-4px);box-shadow:0 26px 70px rgba(23,23,23,.14)}.line-catalog img{width:100%;height:210px;object-fit:cover}.line-catalog article div{padding:20px}.line-catalog small{color:#8a8f94;font-weight:900}.line-catalog span{display:block;margin:14px 0;color:var(--line-accent);font-weight:900;line-height:1.45}.line-catalog a{display:inline-flex;align-items:center;gap:7px;font-weight:950}
      .line-banner,.line-main-site-banner{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:24px;align-items:center;color:#fff;background:linear-gradient(100deg,rgba(23,23,23,.94),rgba(23,23,23,.72)),url("https://images.pexels.com/photos/9338479/pexels-photo-9338479.jpeg?auto=compress&cs=tinysrgb&w=1800") center/cover}.line-banner p,.line-main-site-banner p{max-width:760px;color:#ded7cf}
      .line-cases,.line-advantages,.line-steps{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:16px}.line-cases article,.line-advantages article,.line-steps article{min-height:220px;padding:24px;transition:transform .18s ease,box-shadow .18s ease}.line-cases article>span,.line-steps article>span{display:inline-grid;place-items:center;width:42px;height:42px;margin-bottom:22px;color:#fff;background:var(--line-accent);border-radius:50%;font-weight:950}
      .line-map-section{background:#ededeb}.line-geo{display:grid;grid-template-columns:minmax(280px,.32fr) minmax(0,1fr);gap:24px}.line-geo-card{display:grid;gap:12px}.line-geo-card div{padding:22px;background:var(--line-card);border-radius:9px;border:1px solid var(--line-border)}.line-geo-card strong,.line-metrics strong{display:block;color:var(--line-accent);font-size:42px;line-height:1}.line-russia-map{position:relative;min-height:500px;overflow:hidden;background:radial-gradient(circle at 20% 40%,rgba(252,84,19,.16),transparent 18%),radial-gradient(circle at 70% 38%,rgba(252,84,19,.18),transparent 18%),linear-gradient(135deg,#f9f9f7,#d8d8d2);border:1px solid var(--line-border);border-radius:12px}.line-russia-map:before{content:"";position:absolute;inset:56px;background:rgba(23,23,23,.1);clip-path:polygon(5% 48%,17% 36%,36% 34%,45% 25%,62% 34%,80% 30%,96% 44%,88% 62%,68% 58%,54% 70%,34% 62%,18% 68%)}.line-russia-map span{position:relative;z-index:2;display:inline-flex;margin:18px;padding:8px 10px;background:#fff;border-radius:999px;font-weight:950;box-shadow:0 10px 30px rgba(23,23,23,.12)}
      .line-slider,.line-partners{display:grid;grid-auto-flow:column;grid-auto-columns:minmax(300px,1fr);gap:16px;overflow-x:auto;padding-bottom:10px}.line-slider article{min-height:240px;padding:28px}.line-slider p{color:var(--line-ink);font-size:19px}.line-about{display:grid;grid-template-columns:minmax(0,.8fr) minmax(340px,.72fr);gap:28px;align-items:center;background:#fff}.line-metrics{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.line-metrics article{min-height:150px;padding:22px;background:var(--line-soft);border-radius:9px}.line-advantages svg,.line-contact-list svg{color:var(--line-accent);flex:0 0 auto}.line-partners article{display:grid;place-items:center;min-height:120px;color:var(--line-muted);font-size:22px;font-weight:950}
      .line-faq{display:grid;gap:10px;max-width:1060px}.line-faq details{padding:20px 22px}.line-faq summary{cursor:pointer;font-size:18px;font-weight:950}
      .line-contact-form,.line-contacts{display:grid;grid-template-columns:minmax(0,.72fr) minmax(360px,.72fr);gap:28px;align-items:start}.line-contact-form{color:#fff;background:linear-gradient(100deg,rgba(23,23,23,.94),rgba(23,23,23,.72)),url("https://images.pexels.com/photos/29224600/pexels-photo-29224600.jpeg?auto=compress&cs=tinysrgb&w=1800") center/cover}.line-contact-form p{color:#ded7cf}.line-form{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px;padding:24px;color:var(--line-ink)}.line-form h3,.line-form-wide,.line-form button,.line-form-status{grid-column:1/-1}.line-form label{display:grid;gap:7px;font-weight:900}.line-form input,.line-form textarea,.text-field input,.text-field textarea{width:100%;min-height:46px;padding:0 12px;border:1px solid var(--line-border);border-radius:8px;background:#fff}.line-form textarea,.text-field textarea{min-height:110px;padding-top:12px}.line-form-status{margin:0;color:var(--line-accent);font-weight:900}
      .line-contact-list{display:grid;gap:12px;margin-top:28px}.line-contact-list a,.line-contact-list span{display:flex;align-items:center;gap:10px;color:var(--line-ink);font-size:18px;font-weight:950}.line-contacts iframe{width:100%;min-height:520px;border:0;border-radius:12px;box-shadow:0 20px 60px rgba(23,23,23,.14)}
      .line-footer{display:grid;grid-template-columns:auto 1fr minmax(260px,.34fr);gap:24px;align-items:start;padding:34px clamp(18px,5vw,72px);color:#fff;background:#171717}.line-footer nav a{color:#fff}.line-footer div{display:grid;gap:8px}.line-footer .brand small{color:#bab3aa}

      .calculator-shell{background:linear-gradient(180deg,#fff,#f1f1ee)}.calculator-header{display:grid;grid-template-columns:minmax(0,1fr) minmax(320px,.46fr);gap:28px;align-items:end;margin-bottom:28px}.calculator-header p{max-width:820px;font-size:18px}.calculator-header img{width:100%;height:260px;object-fit:cover;border:1px solid var(--line-border);border-radius:12px;box-shadow:0 20px 60px rgba(23,23,23,.1)}
      .calculator-product{display:grid;grid-template-columns:minmax(0,1fr) minmax(320px,.38fr);gap:22px;align-items:start}.calc-workspace{padding:clamp(22px,3vw,36px)}.calc-summary{position:sticky;top:112px;padding:26px}.calc-progress-line{height:5px;overflow:hidden;background:#e4e4df;border-radius:999px}.calc-progress-line span{display:block;height:100%;background:var(--line-accent);transition:width .26s ease}.calc-steps{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:8px;margin:16px 0 28px}.calc-steps button{display:flex;align-items:center;justify-content:center;gap:8px;min-height:44px;background:#fff;border:1px solid var(--line-border);border-radius:8px;font-weight:950;cursor:pointer}.calc-steps button.is-active{color:#fff;background:var(--line-dark);border-color:var(--line-dark)}.calc-steps span{display:grid;place-items:center;width:26px;height:26px;background:rgba(252,84,19,.12);border-radius:50%;color:var(--line-accent)}
      .calc-panel{min-height:520px}.calc-panel h3{display:flex;align-items:center;gap:10px}.profile-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.profile-card,.option-card,.calc-chip{border:1px solid var(--line-border);background:#fff;border-radius:9px;cursor:pointer;transition:transform .18s ease,box-shadow .18s ease,border-color .18s ease,background .18s ease}.profile-card{display:grid;gap:8px;min-height:164px;padding:18px;text-align:left}.profile-card span{color:var(--line-accent);font-size:12px;font-weight:950}.profile-card strong{font-size:20px}.profile-card small{color:var(--line-muted);line-height:1.45}.profile-card.is-active,.option-card.is-active,.calc-chip.is-active{border-color:rgba(252,84,19,.65);background:#fff6f1;box-shadow:0 16px 42px rgba(252,84,19,.12)}
      .calc-option-group{display:grid;gap:10px;margin:20px 0}.calc-option-group>span{font-weight:950}.calc-chip-row{display:flex;flex-wrap:wrap;gap:8px}.calc-chip{min-height:42px;padding:0 14px;font-weight:950}.option-list{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px;margin:20px 0}.option-card{display:grid;grid-template-columns:22px 1fr auto;gap:10px;align-items:center;min-height:60px;padding:14px;text-align:left}.option-card svg{color:var(--line-accent)}.option-card strong{white-space:nowrap}.text-field{display:grid;gap:8px;margin-top:14px;font-weight:950}.deliverable-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px;margin:22px 0}.deliverable-grid span{padding:14px;background:#f4f4f1;border:1px solid var(--line-border);border-radius:8px;font-weight:850}.lead-status{margin:14px 0 0;color:var(--line-accent);font-weight:950}.calc-controls{display:flex;justify-content:space-between;gap:12px;margin-top:24px}
      .config-preview{display:grid;gap:8px;margin:20px 0;padding:18px;background:linear-gradient(135deg,#24272d,#111318);border-radius:10px}.config-preview i{display:block;height:12px;background:linear-gradient(90deg,#c4c8cc,#777f87);border-radius:999px;box-shadow:inset 0 0 0 1px rgba(255,255,255,.18)}.summary-price{margin:18px 0;padding:18px;color:#fff;background:var(--line-dark);border-radius:10px;font-size:clamp(30px,3vw,44px);font-weight:950}.summary-price small{display:block;margin-top:6px;color:#cfd3d7;font-size:13px}.calc-summary ul{display:grid;gap:10px;margin:0;padding-left:18px;color:#4d5359}.calc-note{display:flex;gap:10px;margin-top:18px;padding:14px;background:#fff6f1;border:1px solid rgba(252,84,19,.25);border-radius:9px;font-weight:850}.calc-note svg{color:var(--line-accent);flex:0 0 auto}

      @media (max-width:1160px){.line-header,.line-hero,.line-geo,.line-about,.line-contact-form,.line-contacts,.line-banner,.line-main-site-banner,.calculator-header,.calculator-product{grid-template-columns:1fr}.line-catalog,.line-cases,.line-advantages,.line-steps{grid-template-columns:repeat(2,minmax(0,1fr))}.calc-summary{position:static}.hero-video-card{min-height:460px}.hero-metrics{grid-template-columns:repeat(2,minmax(0,1fr))}}
      @media (max-width:760px){.line-header{position:static;border-radius:0}.line-header nav,.line-header-contact{justify-content:flex-start;text-align:left}.catalog-dropdown{position:static;width:100%;margin-top:8px;opacity:1;visibility:visible;transform:none;box-shadow:none}.line-hero{padding-top:54px}.line-page h1{font-size:clamp(42px,14vw,64px)}.line-catalog,.line-cases,.line-advantages,.line-steps,.line-metrics,.line-form,.line-footer,.profile-grid,.option-list,.deliverable-grid,.calc-steps{grid-template-columns:1fr}.line-russia-map,.line-contacts iframe,.hero-video-card{min-height:360px}.line-banner,.line-main-site-banner{display:block}.line-banner .line-primary,.line-main-site-banner .line-primary{margin-top:18px}.option-card{grid-template-columns:22px 1fr}}
    `}</style>
  );
}
