export function LinePageStyles() {
  return (
    <style>{`
      .line-page{--line-accent:#fc5413;--line-ink:#171717;--line-paper:#f5f3ee;--line-soft:#ebe7dd;--line-muted:#68645c;--line-card:#fffdf8;--line-border:rgba(23,23,23,.14);color:var(--line-ink);background:var(--line-paper)}
      .line-page h1,.line-page h2,.line-page h3{letter-spacing:0}.line-page h1{max-width:1100px;margin:18px 0 22px;font-size:clamp(46px,7.2vw,106px);line-height:.94}.line-page h2{margin:12px 0 16px;font-size:clamp(34px,5.2vw,76px);line-height:.98}.line-page p{color:var(--line-muted)}
      .line-header{position:fixed;top:18px;left:clamp(16px,3vw,44px);right:clamp(16px,3vw,44px);z-index:90;display:grid;grid-template-columns:auto 1fr auto;gap:20px;align-items:center;min-height:70px;padding:10px 12px;color:#fff;background:rgba(20,20,20,.78);border:1px solid rgba(255,255,255,.14);border-radius:8px;backdrop-filter:blur(18px)}
      .line-header nav,.line-footer nav{display:flex;flex-wrap:wrap;gap:4px;justify-content:center}.line-header nav a,.line-footer nav a{padding:10px 12px;border-radius:7px;transition:background .18s ease,transform .18s ease}.line-header nav a:hover{background:rgba(255,255,255,.1);transform:translateY(-1px)}
      .line-header-contact{display:flex;align-items:center;gap:10px;font-weight:900}.line-header-btn,.line-primary,.line-secondary{display:inline-flex;align-items:center;justify-content:center;gap:9px;min-height:50px;padding:0 20px;border-radius:7px;font-weight:900;transition:transform .18s ease,box-shadow .18s ease}.line-header-btn,.line-primary{color:#fff;background:var(--line-accent);box-shadow:0 18px 42px rgba(252,84,19,.28)}.line-secondary{color:#fff;background:rgba(255,255,255,.14);border:1px solid rgba(255,255,255,.18)}.line-header-btn:hover,.line-primary:hover,.line-secondary:hover{transform:translateY(-2px)}
      .line-hero{position:relative;min-height:100dvh;display:grid;grid-template-columns:minmax(0,1fr) minmax(380px,.42fr);gap:clamp(28px,5vw,72px);align-items:end;padding:136px clamp(18px,5vw,72px) 56px;overflow:hidden;color:#fff;background:#141414}.line-hero-bg{position:absolute;inset:0;background:linear-gradient(90deg,rgba(16,16,16,.96),rgba(16,16,16,.62) 48%,rgba(16,16,16,.9)),url("https://images.pexels.com/photos/36122954/pexels-photo-36122954.jpeg?auto=compress&cs=tinysrgb&w=1800") center/cover;animation:lineVideoMove 12s ease-in-out infinite alternate}.line-hero-bg:after{content:"";position:absolute;inset:0;background:linear-gradient(rgba(255,255,255,.04) 1px,transparent 1px),linear-gradient(90deg,rgba(255,255,255,.035) 1px,transparent 1px);background-size:64px 64px}@keyframes lineVideoMove{from{transform:scale(1)}to{transform:scale(1.06) translateX(-1.2%)}}
      .line-hero-content,.line-hero-panel{position:relative;z-index:2}.line-hero-content p{max-width:760px;color:#ddd6cb;font-size:20px}.line-kicker{display:inline-flex;align-items:center;gap:10px;color:var(--line-accent);font-size:12px;font-weight:900;text-transform:uppercase}.line-kicker:before{content:"";width:34px;height:2px;background:var(--line-accent)}.line-actions{display:flex;flex-wrap:wrap;gap:12px;margin-top:34px}
      .line-hero-panel{overflow:hidden;background:rgba(255,255,255,.1);border:1px solid rgba(255,255,255,.16);border-radius:10px;backdrop-filter:blur(12px)}.line-hero-panel img{width:100%;height:360px;object-fit:cover}.line-hero-panel div{padding:20px}.line-hero-panel strong,.line-hero-panel span{display:block}.line-hero-panel span{margin-top:7px;color:#d8d1c8}
      .line-section,.line-about,.line-main-site-banner,.line-contact-form,.line-contacts,.line-banner{padding:clamp(72px,8vw,118px) clamp(18px,5vw,72px)}.line-section-head{max-width:980px;margin-bottom:36px}
      .line-catalog{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:18px}.line-catalog article,.line-cases article,.line-advantages article,.line-steps article,.line-slider article,.line-partners article,.line-form,.line-faq details{background:var(--line-card);border:1px solid var(--line-border);border-radius:9px;box-shadow:0 20px 60px rgba(23,23,23,.08)}.line-catalog article{overflow:hidden;transition:transform .18s ease,box-shadow .18s ease}.line-catalog article:hover,.line-cases article:hover,.line-advantages article:hover,.line-steps article:hover{transform:translateY(-4px);box-shadow:0 26px 70px rgba(23,23,23,.14)}.line-catalog img{width:100%;height:210px;object-fit:cover}.line-catalog article div{padding:20px}.line-catalog span{display:block;margin:14px 0;color:var(--line-accent);font-weight:900;line-height:1.45}.line-catalog a{display:inline-flex;align-items:center;gap:7px;font-weight:900}
      .line-banner,.line-main-site-banner{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:24px;align-items:center;color:#fff;background:linear-gradient(100deg,rgba(23,23,23,.94),rgba(23,23,23,.72)),url("https://images.pexels.com/photos/9338479/pexels-photo-9338479.jpeg?auto=compress&cs=tinysrgb&w=1800") center/cover}.line-banner p,.line-main-site-banner p{max-width:760px;color:#ded7cf}
      .line-cases,.line-advantages,.line-steps{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:16px}.line-cases article,.line-advantages article,.line-steps article{min-height:220px;padding:24px}.line-cases article>span,.line-steps article>span{display:inline-grid;place-items:center;width:42px;height:42px;margin-bottom:22px;color:#fff;background:var(--line-accent);border-radius:50%;font-weight:900}
      .line-map-section{background:#e9e4da}.line-geo{display:grid;grid-template-columns:minmax(280px,.32fr) minmax(0,1fr);gap:24px}.line-geo-card{display:grid;gap:12px}.line-geo-card div{padding:22px;background:var(--line-card);border-radius:9px;border:1px solid var(--line-border)}.line-geo-card strong,.line-metrics strong{display:block;color:var(--line-accent);font-size:42px;line-height:1}.line-russia-map{position:relative;min-height:500px;overflow:hidden;background:radial-gradient(circle at 20% 40%,rgba(252,84,19,.16),transparent 18%),radial-gradient(circle at 70% 38%,rgba(252,84,19,.18),transparent 18%),linear-gradient(135deg,#f9f7f1,#d8d0c0);border:1px solid var(--line-border);border-radius:12px}.line-russia-map:before{content:"";position:absolute;inset:56px;background:rgba(23,23,23,.1);clip-path:polygon(5% 48%,17% 36%,36% 34%,45% 25%,62% 34%,80% 30%,96% 44%,88% 62%,68% 58%,54% 70%,34% 62%,18% 68%)}.line-russia-map span{position:relative;z-index:2;display:inline-flex;margin:18px;padding:8px 10px;background:#fff;border-radius:999px;font-weight:900;box-shadow:0 10px 30px rgba(23,23,23,.12)}
      .line-slider,.line-partners{display:grid;grid-auto-flow:column;grid-auto-columns:minmax(300px,1fr);gap:16px;overflow-x:auto;padding-bottom:10px}.line-slider article{min-height:240px;padding:28px}.line-slider p{color:var(--line-ink);font-size:19px}.line-about{display:grid;grid-template-columns:minmax(0,.8fr) minmax(340px,.72fr);gap:28px;align-items:center;background:var(--line-card)}.line-metrics{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.line-metrics article{min-height:150px;padding:22px;background:var(--line-soft);border-radius:9px}.line-advantages svg,.line-contact-list svg{color:var(--line-accent);flex:0 0 auto}.line-partners article{display:grid;place-items:center;min-height:120px;color:var(--line-muted);font-size:22px;font-weight:900}
      .line-faq{display:grid;gap:10px;max-width:1060px}.line-faq details{padding:20px 22px}.line-faq summary{cursor:pointer;font-size:18px;font-weight:900}
      .line-contact-form,.line-contacts{display:grid;grid-template-columns:minmax(0,.72fr) minmax(360px,.72fr);gap:28px;align-items:start}.line-contact-form{color:#fff;background:linear-gradient(100deg,rgba(23,23,23,.94),rgba(23,23,23,.72)),url("https://images.pexels.com/photos/29224600/pexels-photo-29224600.jpeg?auto=compress&cs=tinysrgb&w=1800") center/cover}.line-contact-form p{color:#ded7cf}.line-form{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px;padding:24px;color:var(--line-ink)}.line-form h3,.line-form-wide,.line-form button,.line-form-status{grid-column:1/-1}.line-form label{display:grid;gap:7px;font-weight:900}.line-form input,.line-form textarea{width:100%;min-height:46px;padding:0 12px;border:1px solid var(--line-border);border-radius:7px}.line-form textarea{min-height:110px;padding-top:12px}.line-form-status{margin:0;color:var(--line-accent);font-weight:900}
      .line-contact-list{display:grid;gap:12px;margin-top:28px}.line-contact-list a,.line-contact-list span{display:flex;align-items:center;gap:10px;color:var(--line-ink);font-size:18px;font-weight:900}.line-contacts iframe{width:100%;min-height:520px;border:0;border-radius:12px;box-shadow:0 20px 60px rgba(23,23,23,.14)}
      .line-footer{display:grid;grid-template-columns:auto 1fr minmax(260px,.34fr);gap:24px;align-items:start;padding:34px clamp(18px,5vw,72px);color:#fff;background:#171717}.line-footer div{display:grid;gap:8px}.line-footer .brand small{color:#bab3aa}
      @media (max-width:1160px){.line-hero,.line-geo,.line-about,.line-contact-form,.line-contacts,.line-banner,.line-main-site-banner{grid-template-columns:1fr}.line-catalog,.line-cases,.line-advantages,.line-steps{grid-template-columns:repeat(2,minmax(0,1fr))}}
      @media (max-width:760px){.line-header{position:static;grid-template-columns:1fr;border-radius:0;background:#171717}.line-header nav,.line-header-contact{justify-content:flex-start}.line-hero{padding-top:54px}.line-catalog,.line-cases,.line-advantages,.line-steps,.line-metrics,.line-form,.line-footer{grid-template-columns:1fr}.line-russia-map,.line-contacts iframe{min-height:360px}}
    `}</style>
  );
}
